### ISSUE TITLE
Token Decimals Crash 

### ISSUE THREAD

**Issue by sshivaditya2019** [sshivaditya2019/test-public#124]
@0x4007 This error seems familiar: https://github.com/ubiquity-os-marketplace/conversation-rewards/actions/runs/11165001249/job/31035657102#step:7:463
```
Error: Failed to get token decimals for token: 0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d
    at ZB (/home/runner/work/conversation-rewards/conversation-rewards/node_modules/@ubiquibot/permit-generation/dist/core/index-BeQ_V1CH.js:31:1707)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     at async nb (/home/runner/work/conversation-rewards/conversation-rewards/node_modules/@ubiquibot/permit-generation/dist/core/index-BeQ_V1CH.js:31:4773)
     at PermitGenerationModule.transform (/home/runner/work/conversation-rewards/conversation-rewards/src/parser/permit-generation-module.ts:101:25)
     at Processor.runs (/home/runner/work/conversation-rewards/conversation-rewards/src/parser/processor.ts:37:24)
     at runs (/home/runner/work/conversation-rewards/conversation-rewards/src/run.ts:25:5)
 ```

 _Originally posted by @0x4007 in [ubiquity-os-marketplace/daemon-pricing#32 (comment)](https://github.com/ubiquity-os-marketplace/daemon-pricing/issues/32#issuecomment-2399043677)_

**Comment by 0x4007** [comment]
Looks like you need to be careful about not breaking links
